# Generated by Django 4.2.6 on 2023-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=0)),
                ('breadth', models.IntegerField(default=0)),
                ('radius', models.IntegerField(default=0)),
                ('sideLength', models.IntegerField(default=0)),
                ('base', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('pHeight', models.IntegerField(default=0)),
                ('pBase', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
            ],
        ),
    ]
